version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jam_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/joinmarket-webui/jam-standalone:v0.4.0-clientserver-v0.9.11@sha256:3742e15734b91ea520ae7b78c2e6b82aed715bdcda5a786c92efe77ffd89ecc7
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/joinmarket:/root/.joinmarket
    environment:
      RESTORE_DEFAULT_CONFIG: "true"
      REMOVE_LOCK_FILES: "true"
      ENSURE_WALLET: "true"
      APP_USER: umbrel
      APP_PASSWORD: "${APP_PASSWORD}"
      jm_network: $APP_BITCOIN_NETWORK
      jm_rpc_host: $APP_BITCOIN_NODE_IP
      jm_rpc_port: $APP_BITCOIN_RPC_PORT
      jm_rpc_user: $APP_BITCOIN_RPC_USER
      jm_rpc_password: "${APP_BITCOIN_RPC_PASS}"
      jm_rpc_wallet_file: jam_default
      jm_directory_nodes: 3kxw6lf5vf6y26emzwgibzhrzhmhqiw6ekrek3nqfjjmhwznb2moonad.onion:5222,bqlpq6ak24mwvuixixitift4yu42nxchlilrcqwk2ugn45tdclg42qid.onion:5222,coinjointovy3eq5fjygdwpkbcdx63d7vd4g32mw7y553uj3kjjzkiqd.onion:5222,jmarketxf5wc4aldf3slm5u6726zsky52bqnfv6qyxe5hnafgly6yuyd.onion:5222,odpwaf67rs5226uabcamvypg3y4bngzmfk7255flcdodesqhsvkptaid.onion:5222,satoshi2vcg5e2ept7tjkzlkpomkobqmgtsjzegg6wipnoajadissead.onion:5222,shssats5ucnwdpbticbb4dymjzf2o27tdecpes35ededagjpdmpxm6yd.onion:5222,ylegp63psfqh3zk2huckf2xth6dxvh2z364ykjfmvsoze6tkfjceq7qd.onion:5222
